//Colm Woodlock G00341460
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.10 at 09:46:05 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://Models", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.gmit.sw.RMIServer.RMI;
